export const GET_EMPLOYEE = "GET_EMPLOYEES";
export const VIEW_EMPLOYEE = "VIEW_EMPLOYEE";
export const ADD_EMPLOYEE = "ADD_EMPLOYEE";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";